version: "3.8"

services:
  db:
    container_name: postgres_container
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: ECF_Appli_Hopital
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  pg-admin:    
    image: dpage/pgadmin4
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"


volumes:
  db:
    # driver: local